baseURL = "https://tutopourtous.netlify.app/"
languageCode = "fr-fr"
hreflang = "fr-fr"
title = "Tutoriels Pour Tous"
paginate = 4

[params]
dateFormat = "Jan 2, 2006, 3:04PM"

[permalinks]
  posts = "/:title/"